### ISSUE TITLE
How to save data to the data folder

### ISSUE THREAD

**Issue by HuangHam** [nivlab/nivturk#101]
Hi! I have a quick question. I'm using the Nivturk template for prolific. Right now I'm testing it on my local machine and everything is working fine, except when i finish my study, the data is save to the download fold of my mac, but there is no data saved in the data directory of the nivturk folder. Should I modify this line somehow? jsPsych.data.get().localSave('csv', 'mydata.csv');

**Comment by szorowi1** [comment]
Hi @HuangHam, so cool to see you're trying out NivTurk! To confirm, when you are testing your experiment, are you running it directly from the browser or have you started a local Flask server? NivTurk only saves the data when the Flask application is running. The instructions for running and testing your experiment through the Flask app are here: 

https://nivlab.github.io/nivturk/docs/basic-usage/development/#testing-your-experiment

Let me know if that doesn't work and I'll be happy to help troubleshoot.

Best,
Sam (@szorowi1)

**Comment by HuangHam** [comment]
Nivturk is awesome! I am using the terminal to run the app, exactly following this link you sent me. I see the metadata being saved to the metadata folder but the data folder is still empty.

**Comment by szorowi1** [comment]
I see. Can you copy/paste the jsPsych initialization code from your experiment? That is, I'm looking to see the code from your `experiment.html` file that looks like:

```
  // Initialize jsPsych.
  var jsPsych = initJsPsych({
    on_finish: function() {

      // Remove requirement to verify redirect
      window.removeEventListener("beforeunload", verify_unload);

     ...

      if (low_quality) {

        // Save rejected dataset to disk.
        redirect_reject("{{workerId}}", "{{assignmentId}}", "{{hitId}}", "{{code_reject}}");

      } else {

        // Save complete dataset to disk.
        redirect_success("{{workerId}}", "{{assignmentId}}", "{{hitId}}", "{{code_success}}");

      }

    }
  });
```

**Comment by HuangHam** [comment]
here it it: 

var jsPsych = initJsPsych({
      on_finish: function() {

      // Remove requirement to verify redirect
      window.removeEventListener("beforeunload", verify_unload);
      // Add interactions to the data variable
      var interaction_data = jsPsych.data.getInteractionData();
      jsPsych.data.get().addToLast({interactions: interaction_data.json()});
      jsPsych.data.get().localSave('csv', 'data/mydata.csv');
      // Display jsPsych data in viewport.
      // jsPsych.data.displayData();

      if (low_quality) {

        // Save rejected dataset to disk.
        redirect_reject("{{workerId}}", "{{assignmentId}}", "{{hitId}}", "{{code_reject}}");

      } else {

        // Save complete dataset to disk.
        redirect_success("{{workerId}}", "{{assignmentId}}", "{{hitId}}", "{{code_success}}");

      }
    }
    });

**Comment by szorowi1** [comment]
Thank you! All of that looks right. And to confirm, at the end of your experiment, NivTurk is successfully redirecting you to Prolific?

**Comment by HuangHam** [comment]
Oh no, I did not run it on prolific. I ran it on my local machine. So no it didn't redirect me. Is that where the problem is? I simply used my local browser to open: http://130.91.68.123:9000/?PROLIFIC_PID=hh to run the task.

**Comment by szorowi1** [comment]
Oh, my apologies for the confusion: no you don't need to run it on Prolific. When you launch the experiment from the Flask app, if the experiment completes successfully, NivTurk should automatically redirect you at the end of the experiment to Prolific. If you're not experiencing the redirect, then something else is bugged.

**Comment by HuangHam** [comment]
Oh I see. Right no. That is not happening so maybe that's where the problem is? How should I trouble shoot?

**Comment by szorowi1** [comment]
At the end of the experiment, can you check the browser console and see if there is an error? I suspect that'll help us get to the root of this. Otherwise maybe we can quickly hop on Zoom?

**Comment by HuangHam** [comment]
That'd be lovely! here is my zoom: [link hidden for privacy reasons] You can join at anytime

**Comment by szorowi1** [comment]
Post-zoom meeting: We found that the `low_quality` variable was missing. Adding this to `experiment.html` solved the problem. Thanks @HuangHam for your patience!

**Comment by HuangHam** [comment]
Thank you sam for your help! A follow-up development request: adding save csv option (additional to saving as json)
