### ISSUE TITLE
When debug=true, works. Once set debug=false, server gives error

### ISSUE THREAD

**Issue by HuangHam** [nivlab/nivturk#104]
The error is something like can't find the consent form. Why is this happening? I'm using nivturk prolific.

**Comment by szorowi1** [comment]
Hi @HuangHam, can you copy/paste the error Flask is giving you?

**Comment by szorowi1** [comment]
Hi @HuangHam, I am going to close this issue for now as I was unable to reproduce the problem as reported. If you're continuing to run into a problem, feel free to reopen this issue.
