### ISSUE TITLE
Add "Download" button on consent form for participants to keep a copy of the consent form.

### ISSUE THREAD

**Issue by jamie-chiu** [nivlab/nivturk#108]

**Comment by szorowi1** [comment]
@jamie-chiu, thanks for flagging this issue! I think this would be a nice feature to add to NivTurk. 

One point to make is that, if this feature is added, we should also update the [documentation](https://nivlab.github.io/nivturk/docs/basic-usage/development/#consent-forms) to remind experimenters to make their own PDF copy of the consent form (lest they use ours).

**Comment by jamie-chiu** [comment]
I submitted a pull request so I will close this issue. Ended up adding a print function which would also allow participants to save as PDF. This way, experimenters do not need to upload a PDF copy and participants will always save the same consent form as the one they sign.

**Comment by szorowi1** [comment]
Ah, that's a much better idea!
