### ISSUE TITLE
user OS

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#13]
Record user operating system / device.

**Comment by danielbrianbennett** [comment]
Seems like we should be able to do this by referring to the navigator variable (navigator.appVersion). See, e.g.,

https://www.tutorialspoint.com/how-to-find-operating-system-in-the-client-machine-using-javascript

**Comment by danielbrianbennett** [comment]
Or navigator.platform, perhaps: https://stackoverflow.com/questions/9038625/detect-if-device-is-ios

**Comment by szorowi1** [comment]
Seconding your suggestion for using `navigator.userAgent` based on [this tutorial](https://www.w3schools.com/js/js_window_navigator.asp).

Trying to give some thought as to why we want this info. I can think of two immediate reasons:
1. **Debugging**:  If our task fails with a participant, knowing their set up will make it easier to debug.
2. **Exclusion**: If we want to exclude mobile users. 

The first motivation merely requires logging the information. The second motivation requires doing something with the info. It seems detecting a mobile user is [doable](http://detectmobilebrowsers.com/) but nontrivial, and requires periodic updating of regex.  

Another  potential solution, as suggested [here](https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser), is simply logging the size of the screen and preventing users from advancing until their screen has reasonable dimensions. 

In any event, implementing (1) seems reasonable.

**Comment by szorowi1** [comment]
See also: https://github.com/matomo-org/device-detector

**Comment by szorowi1** [comment]
Recording user platform/device with ad6bdc448f41d8a048c660e4633f7f9ad8076d72. 

Turns out Flask includes [platform/browser detection](https://tedboy.github.io/flask/generated/generated/werkzeug.UserAgent.html#werkzeug.UserAgent). Will work on excluding mobile users with next push.

**Comment by szorowi1** [comment]
Mobile users excluded with 95565b2d984c6e18b756224ea353c23056ba3981.
