### ISSUE TITLE
v1.0.0 release

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#36]
- [ ] **Code review**: review, discuss, and develop plan to address any outstanding code issues or deficiencies. 
- [ ] **Documentation**: review wiki, find out-of-date sections, and update to reflect major changes made since January. Maybe even migrate to [readthedocs](https://readthedocs.org/)?

**Comment by szorowi1** [comment]
Code review items (organized by branch, mturk or prolific):

- [x] (All): Intelligent completion tracking, i.e. redirect to complete page after completed 
- [x] (All): Intelligent handling of incognito users pre-experiment
- [x] (All): Error-catching on missing session info for all pages post-init  
- [x] (All): Update error codes
- [x] (All): Fix bot consent bug
- [x] (All): Merge NivTurk functions (e.g. `pass-message`) into single file.
- [x] (All): Fix IP address tracking 
- [x] (All): Script for checking status of data collection (#22) 
- [x] (Prolific): Per-user completion code
- [x] (Prolific): Update completion dynamics (redirect via jsPsych)
- [x] (Prolific): Multiple jsPsych completion events (pass-error, pass-reject, pass-data). Maybe should rename functions.
- [x] (Prolific): Update error page (contact on prolific)

**Comment by szorowi1** [comment]
Code review:

- Fix consent form rejection error message.

**Comment by szorowi1** [comment]
Remove https://github.com/nivlab/nivturk/blob/53afea8f65e1931ab9dc791e4f9803c4b0552e19/app/__init__.py#L91

**Comment by danielbrianbennett** [comment]
Also:
- [ ] Update error messages on prolific to ask participants to return the study and message on prolific rather than emailing us

**Comment by szorowi1** [comment]
Documentation items (incomplete):
- [x] Advanced usage page: pass message to trigger session updates
