### ISSUE TITLE
Debug mode tweak

### ISSUE THREAD

**Issue by danielbrianbennett** [nivlab/nivturk#43]
Currently line 91 of `__init__.py` operates whether debug mode is true or false. Perhaps this flag should only operate if debug == false.

**Comment by szorowi1** [comment]
Let me make sure I understand the issue first: I assume what happened is that, during testing, you ran through an experiment under a worker ID and then reused that worker ID for a subsequent test? In which case, there'd be no `workerId` in the session but a corresponding file (with experiment visit) under that `workerId` in the metadata folder, and the error was raised.

When we were writing v1.0, we made the decision that the typical use case for debug mode was one experiment run-through per unique worker ID. This was done to guarantee a clear mapping between `workerId` and `subId` during testing (though this is also somewhat guaranteed by other code). 

Assuming I understand the inciting incident, do you think we should change the typical use case for debug mode (i.e. one workerId = one run)?

**Comment by danielbrianbennett** [comment]
This came up in the context of testing the advanced use case where we allow the user to press refresh/back prior to some triggering event (e.g., media preload). In this case, other changes are also required but this line was getting in the way of testing. 

Happy to just document all necessary changes elsewhere if there’s a good reason not to change this in a dev branch.

**Comment by danielbrianbennett** [comment]
Actually, that approach (just documenting necessary changes) might be more sensible than changing this for the typical use case. Happy to close this one out.

**Comment by szorowi1** [comment]
Ah, I see! I get it now. There's a couple possible solutions that come to mind:

1. As you've suggested, document the requisite changes for making this work in the docs.
2. Create a new dev branch with this feature added.
3. Update the master branches to add a new entry in `app.ini` that specifies what text the code on [line 91](https://github.com/nivlab/nivturk/blob/a75dc351c390b1f85d31c6a3b204f0f16d730267/app/__init__.py#L91) looks for to exclude participants. This new entry will default to `experiment` but can be changed by the user.

This lattermost solution would be unobtrusive for the average user, but would allow advanced users to customize exclusions as needed.

**Comment by danielbrianbennett** [comment]
Oh, #3 is clever!
