### ISSUE TITLE
branch-standalone v0.1 (discussion)

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#44]
### standalone branch review

**Motivation**

The purpose of the [standalone](https://github.com/nivlab/nivturk/tree/standalone) branch is for running behavioral experiments through the browser with participants recruited from more traditional settings (e.g. university undergraduates, clinic patients, community pool). The expectation is that participants will be directed to the experiment link by the researchers themselves or by the university subject pool software. 

Design thinking for this branch should differ from the other branches given the following:

- _Lower throughput:_ Experiments run with the standalone branch should expect to have few active participants at any point in time. This is especially the case for clinical experiments, where experiments are run with patient supervision. As such, we should assume less computational demand for this branch.
- _Lower malfeasance:_ Experiments run with the standalone branch should expect to have lower risk of active tampering. This is because (a) subject anonymity is not guaranteed for undergraduate participants, and malfeasant behavior can be reported, and (b) participants can expect to be supervised in the case of clinical experiments. As such, we should assume lower risk for this branch. 
- _Higher value:_ Data collected from experiments using the standalone branch may have higher value. This is especially the case for clinical experiments. As such, we should assign higher value to partial datasets for this branch.

**Use Case**

The typical participant experience for an experiment using this branch may look as follows:

> A participant opens the URL that was given to them by the experimenter. If they are not given a user ID, they are directed to a page where they input their user ID. Alternately they may have been provided a link that contains their user ID in the URL. In either event, the participant is directed next to the consent form and then experiment. Once the experiment is started, participants are not allowed to restart the experiment under the same user ID. Once the experiment is complete, participants are directed to a complete page informing them it is safe to close the browser. 

**Review: Major Points**

The major review point I am trying to think through is the primary use case and how that should inform the code. For projects like CCNP and Geha, participants will always be supervised and locking participants out on accidental/intentional reset seems more of a technical hindrance than help. An alternate solution for these situations would be to make sure that all datasets are saved out with timestamps so there's no chance of overwriting data. Separately, if the inputted subject IDs are already anonymised, we do not need separate mappings between workerId and subjectId.

For the case of SONA and undergraduate participants, I begin to see the need for lockouts on accidental/intentional resets. Though the current architecture prevents users from restarting the experiment if they enter the same workerId (by URL or input page), they are free to restart the experiment an infinite number of times if they simply modify their workerId (e.g. workerId_2). I wouldn't put this sort of behavior past a student who was worried about course credit.

I wonder if this suggests some further modifications to the architecture for this branch, where participants are always free to restart the experiment. In this setup, participants are only tagged by their "workerIds" and additionally assigned timestamps on experiment start to prevent overwriting data.

Relatedly, I wonder if all data (partial or complete) should be saved for this branch. Given that we should expect lower demand on the server for these experiments, I do not think partial data saving (e.g. on browser unload) should pose an issue. One possible implementation for this is discussed below. 

In short, I'm wondering if it makes sense to elaborate on the use case some more and proceed from there. I've tagged @jbransonbyers given his experiences with Geha. We can also involve Laura given her likely future use for CCNP.

**Review: Minor Points**

- [x] In [__init__.py](https://github.com/nivlab/nivturk/blob/23bc23997e5c78cb1a2084581418a198dd4c7778/app/__init__.py#L76), I think the mobile user check should precede the workerId check. As it stands, mobile/tablet users without a workerId will be allowed to visit the input page and then proceed to the experiment. 

- [x] As discussed on slack, we can simplify the codebase and remove unused routes. If `redirect_success` and `redirect_reject` do not need to be separate, then this can be collapsed. 

- [x] As pointed out by @lizzytong2589, there's a simple trick for saving partial data if that's of any interest. You can add a save data function into the [beforeunload event](https://github.com/nivlab/nivturk/blob/23bc23997e5c78cb1a2084581418a198dd4c7778/app/templates/experiment.html#L25) such that partial datasets are saved when a participant goes to refresh/close their browser. This is a simple, low-effort fix that can mean saving partial data in the event a user runs into technical issues. (I wouldn't do this for MTurk or Prolific where partial datasets have low value, but may be useful for SONA or CCNP.)

**Comment by danielbrianbennett** [comment]
Thanks for the thorough review, Sam. To distill a couple of high-level design philosophy points from your comments, it sounds like we

- would be happy to diverge from the structure of other branches where it makes the code functionality of the stand-alone branch more straightforward (e.g., in the redirect functions)

- should worry less about server load given the far lower expected demand of this branch (giving us the option to save partial datasets, for instance)

In terms of specific changes, I will:

- [x] Consolidate `redirect_success` and `redirect_reject` into a single `redirect` route (maybe? see comment below)
- [x] Add partial data saving in beforeunload (neat trick)
- [x] Change the order of the checks in `init.py`
- [x] Loosen the strict lockout provisions and instead re-allocate subject IDs on the landing page (this + timestamps on experiment start should give participants flexibility while preserving transparency and ensuring overwrites aren't possible)

The idea of removing the workerId/subId distinction is an interesting one, but I am leaning away from it. My rationale is that, although it is true that for CCNP/Geha we will already have assigned anonymised IDs, we can't guarantee that this will be the case in all use cases. In a use case like sona, for instance, it would be nice to be able to use subjects' student IDs as a workerId without having to worry about stripping that out of the data later for the sake of anonymity in data sharing. 

On the question of participants re-starting the experiment, I am trying to think of ways that we would check for this under this system. My thinking is that if a participant were to repeat with the same worker ID, we should be able to detect this by looking either at (a) the number of distinct subject IDs that they have been assigned in their metadata file (if they restart from the landing page each time using the same workerId), or (b) the number of different timestamped files that correspond to the same subject ID (if they restart the experiment.html page a few times). The question in my mind is whether there is any way for us to check the number of times that a participant has restarted with workerId modifications, short of checking the IP address (which might have problems associated in cases where lots of participants are using a similar IP address, as at a university).

**Comment by danielbrianbennett** [comment]
The last thing I think we might want to work out is what the status of the completion codes and redirect routes should be. I'm inclined to say that we could just drop them completely (since the logic of true versus decoy completions no longer makes much sense here), and replace them with a single all-purpose redirect route. The sole counterexample that worries me is a savvy participant who navigates directly to the complete.html page without doing the experiment. Any thoughts on how to work around this? 

As is stands, the `redirect_success` function takes care of this, which might be a reason to keep it.

**Comment by danielbrianbennett** [comment]
Per our recent conversation, I have replaced the `redirect_success` and `redirect_routes` with a single `save_data` route.

**Comment by szorowi1** [comment]
I've gone through the code and made some suggested changes in #45. Most changes were minor except (1) some reorganization of the routes in `index` to prevent IO errors on participant revisits, and (2) collapsing of the `save_data` and `save_partial_data` routes. The latter isn't necessary, but simplifies the code some. 

I've also set the version back to 0.1. In keeping with previous habits, I'd suggest keeping the version beneath 1.0 until we've had the opportunity to test this out live with actual participants.

Are there any outstanding issues at this point? The only things I can think of is that:
1. We're leaving experimenters to independently verify that participants have completed the experiment. Given the low volume of SONA participants, this doesn't seem too onerous to me but we can revisit this if need be.
2. Savvy incognito participants could still repeat the experiment many times, but I can't imagine why they would do that. 

Short of that, I'm happy with v0.1.

**Comment by danielbrianbennett** [comment]
Thanks, Sam. Yeah, I'm happy with points 1 and 2 there. 

There was one issue with the way that you collapsed the redirect routes. The way it was set up, no matter what status was passed, the participant was redirected to the complete page. The consequence of this was that if a participant acidentally pressed back/refresh during the experiment, then even if they selected not to leave the experiment page in the pop-up dialogue box, they would be redirected to the complete page and would not be able to get back to the experiment. This was my initial reason for keeping the two routes separate. In any case, there is a simple enough fix to resolve this in a single redirect route, which I have implemented in a new commit to the `standalone-v0.1-sz` branch. See what you think; if you're happy with that, I'm happy to merge and close the issue.

**Comment by szorowi1** [comment]
Ah, I see. That's entirely my fault. I only ever tested by closing the page -- never tried continuing the experient after an `onbeforelunload` event. Sorry for the inconvenience!

Otherwise, I think the code looks good. Feel free to merge/close. Thanks for your work on this!
