### ISSUE TITLE
delete load-test branch

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#46]
The load-test branch is hopelessly outdated at this point -- it hasn't been updated since before we switched to a versioning system. We've got a pretty good feel for what our servers can handle, and the load-test branch was never integrated with jsPsych. 

@danielbrianbennett, any reason to keep it?

**Comment by danielbrianbennett** [comment]
Good point. Yep, I'm happy to drop it.

**Comment by szorowi1** [comment]
Consider it dropped!
