### ISSUE TITLE
Consent form

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#6]
Let's make sure the template consent form is the most up-to-date version.

**Comment by danielbrianbennett** [comment]
I made some inroads on this. The only thing remaining is to work out which email address to refer people to in the case of technical issues. We were talking about making a new gmail account for this?

**Comment by szorowi1** [comment]
It might not be a bad idea to have fully separate accounts (gmail, mturk, turkprime) strictly for psychiatry studies. We can double check with Yael if she has a preference.

**Comment by szorowi1** [comment]
With Yael's approval, if we can push the new consent form changes to the default NivTurk branch, I think we can close this!

**Comment by danielbrianbennett** [comment]
Done!
