### ISSUE TITLE
Documentation - empty cookbook

### ISSUE THREAD

**Issue by karnigili** [nivlab/nivturk#63]

**Comment by szorowi1** [comment]
- message passing documented in 6366d78161c29694b8e16f36c71c1ba611a4ccf9.
- online rejections documented in 4edbe6eabc46d4d29b24c6df0b47df8b0003c8e4.
- participant monitoring documented in 3056d0bcc5a50fd24c32fb43630ec0c568286a2d.
- longitudinal data collection documented in 13b4f92eda03ba0a63566a08ba99616694f2b784.
- multiple restarts documented in 9bcb8b9a1d916d306a03fe02e5daadfc032be3b5.
- variable passing documented in 9d176bce2a6e9766fa9a153dd02a65e9a8faf322.

**Comment by szorowi1** [comment]
@karnigili, when you have a chance would you mind taking a look at some of the cookbook recipes? https://nivlab.github.io/nivturk/docs/cookbook

**Comment by szorowi1** [comment]
With #73, considering this issue addressed.
