### ISSUE TITLE
jspsych 7.2

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#80]
it's that time. jsPsych is now up to v7.1. Should we update? Thoughts? @danielbrianbennett @karnigili

**Comment by danielbrianbennett** [comment]
I’m happy to put it on the table! I haven’t been keeping up with the release notes, though — what extra features come with the upgrade, and what are the implications for backwards compatibility?

**Comment by szorowi1** [comment]
For the sake of consistency, until we are ready to update all of the tasks in [jspsych-demos](https://github.com/nivlab/jspsych-demos) to jsPsych version 7.2, we will be holding NivTurk at jsPsych v6.3. We can reopen the issue when the time comes.

**Comment by karnigili** [comment]
just saw (sry). I will start a 7.2 branch and slowly start updating the demos:) will keep you posted. I think keeping things up-to-date is important enough.

**Comment by szorowi1** [comment]
Just to make sure everyone is on the same page, I've started a [NivTurk v1.2 branch](https://github.com/nivlab/nivturk/tree/nivturk-v1.2-prolific) that includes upgrading the default jsPsych library from v6.3 to v7.2. So that is being taken care of on the NivTurk side.

The [jspsych-demos](https://github.com/nivlab/jspsych-demos/) issue is a whole other can of worms I could definitely use help with. Converting every task from v6.3 to v7.2 is going to be a colossal amount of work.
