### ISSUE TITLE
Log URL tampering

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk#9]
We've noticed some Turkers attempt to manipulate the URL. Currently this kicks participants from the experiment, but without logging the identity of the tamperer. This would be helpful information as we could add them to a TurkPrime universal exclude list.

A fix should be relatively simple. Anyone being redirected to one of the error pages should have a note written to their metadata.

**Comment by danielbrianbennett** [comment]
I think that's a good idea. I'm sure you've thought thought of this, but we should make sure that the note we write includes the error number. We want to make sure we aren't unfairly excluding those who just hit Back, for instance.

**Comment by szorowi1** [comment]
That's an important point I hadn't thought of. It shouldn't be very hard to guarantee this, but might require more thought than anticipated. We can chat more offline.

**Comment by szorowi1** [comment]
I've attempted a fix here in a new experimental branch, fbf7109e7750e7136757a96a1d71775ee0adc63c. Let's discuss this week.

**Comment by szorowi1** [comment]
Fixed with #10

**Comment by szorowi1** [comment]
Reopening to fix a few issues. The current kick-out pipeline is perhaps too restrictive.

**Comment by szorowi1** [comment]
More graceful pipeline implemented in 95565b2d984c6e18b756224ea353c23056ba3981.
