### ISSUE TITLE
"Basic Usage" section in the documentation disappeared

### ISSUE THREAD

**Issue by HuangHam** [nivlab/nivturk#97]
Hi. I just noticed that the "Basic Usage" section in the Nivturk documentation disappeared. It was fine yesterday but when I opened the page today it's all gone.

**Comment by szorowi1** [comment]
Hi @HuangHam, thanks so much for flagging this issue! While making some improvements to the docs, I accidentally hid the "basic-usage" pages. It should all be fixed now --- try refreshing the docs page. If the error persists, feel free to reopen the issue.

Thanks!
-Sam (@szorowi1)
